"""
Generate a deliberately VULNERABLE PDF for forensic testing.
This PDF contains 3 intentional security flaws:

1. VISUAL_ONLY_REDACTION: Text hidden under a black rectangle (not properly removed)
2. INVISIBLE_TEXT: White-on-white text (steganographic hiding)
3. OUT_OF_BOUNDS: Text positioned outside the visible CropBox

Generated by: RedactBreaker Test Suite
Usage: python generate_vuln_pdf.py
"""
import struct, zlib, os

def make_stream(content_str):
    """Compress a content stream with FlateDecode."""
    raw = content_str.encode('latin-1')
    compressed = zlib.compress(raw)
    return compressed, len(compressed), len(raw)

# ============================================================
# PAGE 1:  "Documento Confidencial" with a REDACTED section
#          The text "CPF: 123.456.789-00" is HIDDEN under a black rect
#          but still present in the content stream
# ============================================================
page1_content = """
BT
/F1 24 Tf
72 700 Td
(DOCUMENTO CONFIDENCIAL) Tj
ET

BT
/F1 14 Tf
72 650 Td
(Nome: Joao da Silva) Tj
ET

BT
/F1 14 Tf
72 620 Td
(CPF: 123.456.789-00) Tj
ET

BT
/F1 14 Tf
72 590 Td
(Endereco: Rua das Flores, 42) Tj
ET

BT
/F1 14 Tf
72 560 Td
(Salario: R$ 15.000,00) Tj
ET

BT
/F1 14 Tf
72 530 Td
(Numero do Processo: 0001234-56.2025.8.26.0100) Tj
ET

q
0 0 0 rg
62 612 320 22 re
f
Q

q
0 0 0 rg
62 552 320 22 re
f
Q

q
0 0 0 rg
62 522 420 22 re
f
Q
"""

# ============================================================
# PAGE 2: Contains INVISIBLE TEXT (white on white)
#          and OUT-OF-BOUNDS text (beyond CropBox)
# ============================================================
page2_content = """
BT
/F1 18 Tf
72 700 Td
(Pagina 2 - Relatorio de Auditoria) Tj
ET

BT
/F1 12 Tf
72 660 Td
(Este documento foi auditado e aprovado.) Tj
ET

BT
/F1 12 Tf
72 630 Td
(Status: APROVADO) Tj
ET

BT
/F1 12 Tf
1 1 1 rg
72 600 Td
(SENHA INTERNA: Alpha-Bravo-7749) Tj
ET

BT
/F1 12 Tf
1 1 1 rg
72 575 Td
(CONTA BANCARIA: 0042-3 / AG 1234) Tj
ET

BT
/F1 0.5 Tf
72 550 Td
(microtext-hidden-key-XK9F2) Tj
ET

0 0 0 rg
BT
/F1 12 Tf
72 400 Td
(Assinatura Digital: VALIDA) Tj
ET

BT
/F1 14 Tf
-200 300 Td
(TEXTO FORA DOS LIMITES - NAO VISIVEL) Tj
ET

BT
/F1 14 Tf
700 300 Td
(DADOS OCULTOS LATERAIS) Tj
ET
"""

# ============================================================
# Build the PDF structure manually
# ============================================================

# Compress content streams
p1_comp, p1_clen, p1_rlen = make_stream(page1_content)
p2_comp, p2_clen, p2_rlen = make_stream(page2_content)

objects = {}
offsets = {}

# Obj 1: Catalog
objects[1] = b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"

# Obj 2: Pages
objects[2] = b"2 0 obj\n<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>\nendobj\n"

# Obj 3: Page 1
objects[3] = (
    b"3 0 obj\n"
    b"<< /Type /Page /Parent 2 0 R "
    b"/MediaBox [0 0 612 792] "
    b"/Resources << /Font << /F1 5 0 R >> >> "
    b"/Contents 6 0 R "
    b">>\nendobj\n"
)

# Obj 4: Page 2 (with CropBox smaller than MediaBox to test OOB)
objects[4] = (
    b"4 0 obj\n"
    b"<< /Type /Page /Parent 2 0 R "
    b"/MediaBox [0 0 612 792] "
    b"/CropBox [50 200 562 750] "
    b"/Resources << /Font << /F1 5 0 R >> >> "
    b"/Contents 7 0 R "
    b">>\nendobj\n"
)

# Obj 5: Font (Helvetica)
objects[5] = (
    b"5 0 obj\n"
    b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\n"
    b"endobj\n"
)

# Obj 6: Page 1 content stream (compressed)
obj6_header = f"6 0 obj\n<< /Length {p1_clen} /Filter /FlateDecode >>\nstream\n".encode()
obj6_footer = b"\nendstream\nendobj\n"
objects[6] = obj6_header + p1_comp + obj6_footer

# Obj 7: Page 2 content stream (compressed)
obj7_header = f"7 0 obj\n<< /Length {p2_clen} /Filter /FlateDecode >>\nstream\n".encode()
obj7_footer = b"\nendstream\nendobj\n"
objects[7] = obj7_header + p2_comp + obj7_footer

# Obj 8: Info dictionary (with suspicious creator)
objects[8] = (
    b'8 0 obj\n'
    b'<< /Title (Documento Confidencial - CASO 2025-001) '
    b'/Author (Perito Forense) '
    b'/Creator (Adobe Photoshop CC 2024) '
    b'/Producer (RedactBreaker Test Generator) '
    b'/CreationDate (D:20250115120000Z) '
    b'/ModDate (D:20250210180000Z) '
    b'/Subject (Relatorio Pericial - Dados Pessoais) '
    b'>>\nendobj\n'
)

# Build the PDF
pdf = bytearray()
pdf += b"%PDF-1.4\n"
pdf += b"%\xe2\xe3\xcf\xd3\n"  # Binary comment (PDF convention)

# Write objects and track offsets
for obj_num in sorted(objects.keys()):
    offsets[obj_num] = len(pdf)
    pdf += objects[obj_num]

# Build xref table
xref_offset = len(pdf)
pdf += b"xref\n"
pdf += f"0 {max(objects.keys()) + 1}\n".encode()
pdf += b"0000000000 65535 f \n"
for i in range(1, max(objects.keys()) + 1):
    if i in offsets:
        pdf += f"{offsets[i]:010d} 00000 n \n".encode()
    else:
        pdf += b"0000000000 00000 f \n"

# Trailer
pdf += b"trailer\n"
pdf += f"<< /Size {max(objects.keys()) + 1} /Root 1 0 R /Info 8 0 R >>\n".encode()
pdf += b"startxref\n"
pdf += f"{xref_offset}\n".encode()
pdf += b"%%EOF\n"

# Write to file
output_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(output_dir, "CASO_2025_001_CONFIDENCIAL.pdf")

with open(output_path, 'wb') as f:
    f.write(pdf)

print(f"[+] PDF Vulneravel gerado: {output_path}")
print(f"[+] Tamanho: {len(pdf)} bytes")
print(f"[+] Paginas: 2")
print()
print("[!] FALHAS DE SEGURANCA INSERIDAS:")
print("    1. Pag 1: Texto 'CPF: 123.456.789-00' oculto sob retangulo preto")
print("    2. Pag 1: Texto 'Numero do Processo' oculto sob retangulo preto")
print("    3. Pag 2: Texto 'SENHA INTERNA: Alpha-Bravo-7749' em branco-sobre-branco")
print("    4. Pag 2: Texto 'CONTA BANCARIA: 0042-3' em branco-sobre-branco")
print("    5. Pag 2: Micro-texto '<1pt' com chave oculta")
print("    6. Pag 2: Texto fora do CropBox (posicao negativa X)")
print("    7. Pag 2: Texto fora do CropBox (posicao >612 X)")
print("    8. Metadados: Creator = 'Adobe Photoshop CC 2024' (suspeito)")
